#!/usr/bin/env python3
"""Generate the Claude apps versions of the writing system from the plugin.

Two outputs, both derived from files under plugins/gborges-standard so the
rules have one source:

  chat/instructions-for-claude.md   paste into Settings, Instructions for Claude
  chat/dist/writing-voice.zip       upload at Customize, Skills, Upload a skill

Every edit this script makes to the plugin text is an anchored replacement.
A missing anchor raises instead of passing the original through, so a change
in the plugin that invalidates a chat rewrite fails the build here rather
than shipping stale text.
"""

import re
import shutil
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHAT = REPO / "chat"
PLUGIN = REPO / "plugins" / "gborges-standard"
STYLE = PLUGIN / "output-styles" / "plain-english.md"
SKILL_DIR = PLUGIN / "skills" / "writing-voice"
DIST = CHAT / "dist"

# Sections of the output style that mean nothing in a chat app. The apps do
# not write commits, spawn no subagents, and expose no slash command for the
# skill, so "The second pass" gets a chat rewrite below.
DROP_SECTIONS = ("Git", "Subagents", "The second pass")

# Replaces the dropped "The second pass" section. Same rule, minus the
# subagent bullet, plus the note that the mechanical scan needs code
# execution turned on in the app.
SECOND_PASS = """## The second pass

- These rules are the first pass, and the only pass a chat reply gets.
- Every artifact gets a second pass before it ships, whatever its length.
  An artifact is any prose that lives on after the turn: a doc, a spec, a
  plan, an audit, a note, a comment someone will post. Run the
  writing-voice skill's two passes on a draft. The skill holds the
  mechanical scan (check.py) and the full ruleset with carve-outs. The scan
  needs code execution turned on. Without that, run the reading-effort pass
  by hand. Never announce that the passes ran.
"""

# Chat-only preamble. The apps can search the web, and this names the
# sources a reply never cites.
BANNED_SOURCES = """# Banned Sources

- Grokipedia (and any similar AI source)
"""

BANNER = """<!-- Generated by chat/build.py. Edit the plugin files, not this one. -->
"""

# (file, anchor, replacement). Anchors are exact substrings of the plugin
# text. Each must appear exactly once.
SKILL_EDITS = [
    (
        "SKILL.md",
        "Chat replies never get it, since the output style alone shapes them.",
        "Chat replies never get it, since the profile instructions alone shape them.",
    ),
    (
        "SKILL.md",
        """The Plain English output style already shapes every sentence (it sits in the
system prompt of every session). That is one pass, written and sent.""",
        """The Plain English instructions in the profile already shape every sentence.
That is one pass, written and sent.""",
    ),
    (
        "SKILL.md",
        """A chat reply never gets the ritual. The output style shapes it as it is
written, and that is the whole treatment.""",
        """A chat reply never gets the ritual. The profile instructions shape it as it
is written, and that is the whole treatment.""",
    ),
    (
        "SKILL.md",
        "The output style alone shapes a chat reply.",
        "The profile instructions alone shape a chat reply.",
    ),
    (
        "SKILL.md",
        "The output style and this skill load in the main conversation only.",
        "The profile instructions and this skill load in the main conversation only.",
    ),
    (
        "SKILL.md",
        """2. **Pass 1, the mechanical scan.** Run `python3 <base>/scripts/check.py
   <draft>`, where `<base>` is this skill's base directory, printed when the
   skill loads. The script flags banned strings and overpacked sentences,""",
        """2. **Pass 1, the mechanical scan.** Run `python3 scripts/check.py <draft>`
   from this skill's directory. It needs code execution. When that is off,
   skip to pass 2. The script flags banned strings and overpacked sentences,""",
    ),
]


def split_sections(body):
    """Return [(heading_or_None, text)] split on level-two headings."""
    parts = re.split(r"^## (.+)$", body, flags=re.M)
    out = [(None, parts[0])]
    for i in range(1, len(parts), 2):
        out.append((parts[i], parts[i + 1]))
    return out


def build_instructions():
    text = STYLE.read_text()
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    if body == text:
        raise SystemExit(f"no frontmatter found in {STYLE}")

    kept = []
    seen = set()
    for heading, chunk in split_sections(body):
        if heading is None:
            kept.append(chunk.strip())
            continue
        seen.add(heading)
        if heading in DROP_SECTIONS:
            if heading == "The second pass":
                kept.append(SECOND_PASS.rstrip())
            continue
        kept.append(f"## {heading}\n\n{chunk.strip()}")

    missing = [s for s in DROP_SECTIONS if s not in seen]
    if missing:
        raise SystemExit(f"expected sections gone from {STYLE}: {missing}")

    out = BANNER + "\n" + BANNED_SOURCES + "\n" + "\n\n".join(kept) + "\n"
    (CHAT / "instructions-for-claude.md").write_text(out)
    return len(out) - len(BANNER) - 1


def build_skill_zip():
    staging = DIST / "writing-voice"
    if DIST.exists():
        shutil.rmtree(DIST)
    shutil.copytree(SKILL_DIR, staging)

    for name, anchor, replacement in SKILL_EDITS:
        path = staging / name
        text = path.read_text()
        if text.count(anchor) != 1:
            raise SystemExit(
                f"anchor appears {text.count(anchor)} times in {name}, expected 1:\n"
                f"  {anchor.splitlines()[0]!r}"
            )
        path.write_text(text.replace(anchor, replacement))

    archive = DIST / "writing-voice.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
        for path in sorted(staging.rglob("*")):
            if path.is_file():
                z.write(path, path.relative_to(DIST))
    shutil.rmtree(staging)
    return archive


def main():
    chars = build_instructions()
    archive = build_skill_zip()
    print(f"chat/instructions-for-claude.md  {chars} characters")
    print(f"{archive.relative_to(REPO)}  {archive.stat().st_size} bytes")
    if chars > 4000:
        print(
            "warning: the Instructions for Claude field truncates long text. "
            "Trim a section or move it into the skill.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
