#!/usr/bin/env python3
"""Generate the Claude apps versions of the writing system from the plugin.

Two outputs, both derived from files under plugins/gborges-standard so the
rules have one source:

  chat/instructions-for-claude.md   paste into Settings, Instructions for Claude
  chat/dist/writing-voice.zip       upload at Customize, Skills, Upload a skill

Every edit this script makes to the plugin text is an anchored replacement.
A missing anchor raises instead of passing the original through, so a change
in the plugin that invalidates a chat rewrite fails the build here rather
than shipping stale text.
"""

import re
import shutil
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHAT = REPO / "chat"
PLUGIN = REPO / "plugins" / "gborges-standard"
STYLE = PLUGIN / "output-styles" / "plain-english.md"
SKILL_DIR = PLUGIN / "skills" / "writing-voice"
DIST = CHAT / "dist"

# Sections of the output style that mean nothing in a chat app. The apps do
# not write commits, and the style's pointer at the skill assumes a slash
# command that does not exist there.
DROP_SECTIONS = ("Git", "Deliverables")

# Replaces the dropped "Deliverables" section. The apps spawn no subagents
# and their replies rarely ship deliverables, so the chat version keeps only
# the document rule.
LONG_DOCUMENTS = """## Long documents

Before shipping any document longer than a few paragraphs (an audit, a spec,
a plan, a piece of writing someone will read twice), run the writing-voice
skill's two passes on a draft. The skill holds the full ruleset with its
carve-outs. Its mechanical scan needs code execution turned on. Without
that, run the reading-effort pass by hand.
"""

BANNER = """<!-- Generated by chat/build.py. Edit the plugin files, not this one. -->
"""

# (file, anchor, replacement). Anchors are exact substrings of the plugin
# text. Each must appear exactly once.
SKILL_EDITS = [
    (
        "SKILL.md",
        "Ordinary chat replies are covered by the Plain English output style and do not need this skill.",
        "Short chat replies do not need this skill.",
    ),
    (
        "SKILL.md",
        """The Plain English output style already shapes every sentence (it rides in the
system prompt of every session). This skill is the heavier ritual for
documents, because prose someone will read twice deserves two passes before
it ships.""",
        """The Plain English instructions in the profile already shape every sentence.
This skill is the heavier ritual for documents, because prose someone will
read twice deserves two passes before it ships.""",
    ),
    (
        "SKILL.md",
        """2. **Pass 1, the mechanical scan.** Run `python3 <base>/scripts/check.py
   <draft>`, where `<base>` is this skill's base directory, printed when the
   skill loads. The script flags banned strings and overpacked sentences,""",
        """2. **Pass 1, the mechanical scan.** Run `python3 scripts/check.py <draft>`
   from this skill's directory. It needs code execution. When that is off,
   skip to pass 2. The script flags banned strings and overpacked sentences,""",
    ),
]


def split_sections(body):
    """Return [(heading_or_None, text)] split on level-two headings."""
    parts = re.split(r"^## (.+)$", body, flags=re.M)
    out = [(None, parts[0])]
    for i in range(1, len(parts), 2):
        out.append((parts[i], parts[i + 1]))
    return out


def build_instructions():
    text = STYLE.read_text()
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    if body == text:
        raise SystemExit(f"no frontmatter found in {STYLE}")

    kept = []
    seen = set()
    for heading, chunk in split_sections(body):
        if heading is None:
            kept.append(chunk.rstrip())
            continue
        seen.add(heading)
        if heading in DROP_SECTIONS:
            if heading == "Deliverables":
                kept.append(LONG_DOCUMENTS.rstrip())
            continue
        kept.append(f"## {heading}\n\n{chunk.strip()}")

    missing = [s for s in DROP_SECTIONS if s not in seen]
    if missing:
        raise SystemExit(f"expected sections gone from {STYLE}: {missing}")

    out = BANNER + "\n\n".join(kept) + "\n"
    (CHAT / "instructions-for-claude.md").write_text(out)
    return len(out) - len(BANNER) - 1


def build_skill_zip():
    staging = DIST / "writing-voice"
    if DIST.exists():
        shutil.rmtree(DIST)
    shutil.copytree(SKILL_DIR, staging)

    for name, anchor, replacement in SKILL_EDITS:
        path = staging / name
        text = path.read_text()
        if text.count(anchor) != 1:
            raise SystemExit(
                f"anchor appears {text.count(anchor)} times in {name}, expected 1:\n"
                f"  {anchor.splitlines()[0]!r}"
            )
        path.write_text(text.replace(anchor, replacement))

    archive = DIST / "writing-voice.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
        for path in sorted(staging.rglob("*")):
            if path.is_file():
                z.write(path, path.relative_to(DIST))
    shutil.rmtree(staging)
    return archive


def main():
    chars = build_instructions()
    archive = build_skill_zip()
    print(f"chat/instructions-for-claude.md  {chars} characters")
    print(f"{archive.relative_to(REPO)}  {archive.stat().st_size} bytes")
    if chars > 4000:
        print(
            "warning: the Instructions for Claude field truncates long text. "
            "Trim a section or move it into the skill.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
